name: Build VeloFetch EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # 3.12を指定
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter Pillow
          pip install nuitka zstandard

      - name: Build EXE with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: VeloFetch.py
          mode: onefile
          standalone: true
          windows-disable-console: true
          enable-plugins: tk-inter
          # Python 3.12のパス構造に対応
          include-data-dir: ${{ env.pythonLocation }}/Lib/site-packages/customtkinter=customtkinter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VeloFetch-Windows-EXE
          path: build/*.exe
